import { afterEach, describe, expect, it, vi } from "vitest";
import { buildBot } from "../src/bot.js";
import { fetchPrice } from "../src/domain.js";
import { runSpec } from "../src/toolkit/harness/index.js";
import type { Watch } from "../src/domain.js";

const btc: Watch = { ticker: "BTC", name: "Bitcoin", id: "bitcoin" };

function response(status: number, body: unknown, headers: Record<string, string> = {}) {
  return {
    ok: status >= 200 && status < 300,
    status,
    headers: new Headers(headers),
    json: async () => body,
  } as unknown as Response;
}

afterEach(() => vi.restoreAllMocks());

describe("price feed resilience", () => {
  it("retries a transient provider failure and returns the live quote", async () => {
    const fetchMock = vi.spyOn(globalThis, "fetch")
      .mockResolvedValueOnce(response(503, {}))
      .mockResolvedValueOnce(response(200, { bitcoin: { usd: 60_000, usd_24h_change: 1.25 } }));

    await expect(fetchPrice(btc)).resolves.toEqual({ price: 60_000, change: 1.25 });
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it("honors Retry-After for a rate limit before retrying", async () => {
    const fetchMock = vi.spyOn(globalThis, "fetch")
      .mockResolvedValueOnce(response(429, {}, { "retry-after": "0" }))
      .mockResolvedValueOnce(response(200, { bitcoin: { usd: 61_000, usd_24h_change: -0.5 } }));

    await expect(fetchPrice(btc)).resolves.toEqual({ price: 61_000, change: -0.5 });
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  it("serves a cached quote on /price but never hides an unavailable feed", async () => {
    const fetchMock = vi.spyOn(globalThis, "fetch")
      .mockResolvedValueOnce(response(200, { bitcoin: { usd: 60_000, usd_24h_change: 1.25 } }))
      .mockRejectedValue(new Error("provider offline"));
    const result = await runSpec(await buildBot("test-token"), {
      name: "cached quote after outage",
      steps: [
        { send: { callback: "watch:add" }, expect: [{ method: "sendMessage" }] },
        { send: { callback: "watch:add:BTC" }, expect: [{ method: "sendMessage" }] },
        { send: { text: "/price BTC" }, expect: [{ method: "sendMessage", payload: { text: "BTC: $60,000 (+1.25% 24h)" } }] },
        { send: { text: "/price BTC" }, expect: [{ method: "sendMessage" }] },
      ],
    });

    // The harness uses subset matching; assert the exact user-visible outage note
    // separately because its timestamp is intentionally generated by the clock.
    expect(result.ok).toBe(true);
    const cachedText = result.steps[3]?.captured.find((call) => call.method === "sendMessage")?.payload.text;
    expect(typeof cachedText).toBe("string");
    expect(cachedText as string).toContain("Last known price (");
    expect(cachedText as string).toContain("data may be stale due to feed outage.");
    expect(fetchMock).toHaveBeenCalledTimes(5);
  });
});
